### ISSUE TITLE
Where to put my badge class file ?

### ISSUE THREAD

**Issue by tasosxak** [pinax/pinax-badges#33]
Hi,

After hours of debugging, I noticed that my badge class was not registered. I noticed that the "badges.register(FirstJarBadge)" command is never executed. 

my badge class (badges.py):
```
from pinax.badges.base import Badge, BadgeAwarded
from pinax.badges.registry import badges

class FirstCarBadge(Badge):
    slug = "firstcar"
    description = "Buy a car."
    levels = [
        "Bronze",
    ]
    events = [
        "firstcar_awarded",
    ]
    multiple = False

    def award(self, **state):
        user = state["user"]
        number_of_cars = user.car_set.all().count()
        print(number_of_cars)
        if number_of_cars > 0:
            return BadgeAwarded()
        

badges.register(FirstCarBadge)
```

my view where I call `possible_award_badge` function:
```
def buy_a_car(request):
      # code
      badges.possibly_award_badge("firstcar_awarded", user=request.user)

```

Also, README.md doesn't specify the location of badges.py.

**Comment by KatherineMichel** [comment]
Sorry for slow response. Have been looking through the code, but not sure the answer atm. Does the view.py file have the proper imports at the top? @tasosxak

**Comment by tasosxak** [comment]
Yes, I had to import this file.
Thanks, closed.
